name: laughterclub
description: "Laughter Club, University of Chittagong"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  syncfusion_flutter_pdf: ^25.2.5
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/PinyonScript-Regular.ttf


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
